theme: jekyll-theme-minimal
title: R Contributor Site
logo: /assets/img/Rlogo.svg
description:
show_downloads: false
github:
  is_project_page: false
owner_url: working-group
owner_name: the R Contribution Working Group
twitter: https://twitter.com/R_Contributors
github: https://github.com/r-devel/
navigation:
  - title: Home
    url: /
  - title: Slack Group
    url: slack
  - title: Events
    url: events
  - title: Tutorials
    url: tutorials
  - title: Guide to R Development
    url: https://contributor.r-project.org/rdevguide/
  - title: R Contribution Working Group
    url: working-group
  - title: R Developer Page
    url: https://developer.r-project.org/
  - title: R Developer Blog
    url: https://developer.r-project.org/Blog/public/
  - title: R SVN CI Dashboard
    url: https://contributor.r-project.org/svn-dashboard
